services:
  backend:
    build: backend
    ports:
      - "9000:9000"
    environment:
      - APPID=${APPID}
    volumes:
      - ./backend/src:/usr/src/app/src
  frontend:
    build: frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/src:/usr/src/app/src